config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  resource :pages, only: [] do
    collection do
      get :profile
      get :pricing
    end
  end

  resource :dashboard, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show; end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action  :authenticate_user!

  def home; end

  def pricing; end

  def profile; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="EmpBook Sample Application on Rails with Argon Design System">
    <meta name="author" content="HASH32">

    <title><%= AppSettings::SITE_NAME %></title>
    <link href="/favicon.png" rel="icon" type="image/png">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|Lobster" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header-global">
      <nav id="navbar-main" class="navbar navbar-main navbar-expand-lg navbar-transparent navbar-light headroom">
        <div class="container">
          <%= link_to AppSettings::SITE_NAME, root_path, class: 'navbar-brand mr-lg-5' %>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse" id="navbar_global">
            <div class="navbar-collapse-header">
              <div class="row">
                <div class="col-6 collapse-brand">
                  <a href="../index.html">
                    <%= image_tag 'brand/white.png' %>
                  </a>
                </div>
                <div class="col-6 collapse-close">
                  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
                    <span></span>
                    <span></span>
                  </button>
                </div>
              </div>
            </div>
            <ul class="navbar-nav navbar-nav-hover align-items-lg-center">
              <li class="nav-item dropdown">
                <a href="#" class="nav-link" data-toggle="dropdown" href="#" role="button">
                  <i class="ni ni-ui-04 d-lg-none"></i>
                  <span class="nav-link-inner--text">Components</span>
                </a>
                <div class="dropdown-menu dropdown-menu-xl">
                  <div class="dropdown-menu-inner">

                    <a href="https://demos.creative-tim.com/argon-design-system/docs/getting-started/overview.html" class="media d-flex align-items-center">
                      <div class="icon icon-shape bg-gradient-primary rounded-circle text-white">
                        <i class="ni ni-spaceship"></i>
                      </div>
                      <div class="media-body ml-3">
                        <h6 class="heading text-primary mb-md-1">Getting started</h6>
                        <p class="description d-none d-md-inline-block mb-0">Learn how to use Argon compiling Scss, change brand colors and more.</p>
                      </div>
                    </a>

                    <a href="https://demos.creative-tim.com/argon-design-system/docs/foundation/colors.html" class="media d-flex align-items-center">
                      <div class="icon icon-shape bg-gradient-success rounded-circle text-white">
                        <i class="ni ni-palette"></i>
                      </div>
                      <div class="media-body ml-3">
                        <h6 class="heading text-primary mb-md-1">Foundation</h6>
                        <p class="description d-none d-md-inline-block mb-0">Learn more about colors, typography, icons and the grid system we used for Argon.</p>
                      </div>
                    </a>

                    <a href="https://demos.creative-tim.com/argon-design-system/docs/components/alerts.html" class="media d-flex align-items-center">
                      <div class="icon icon-shape bg-gradient-warning rounded-circle text-white">
                        <i class="ni ni-ui-04"></i>
                      </div>
                      <div class="media-body ml-3">
                        <h5 class="heading text-warning mb-md-1">Components</h5>
                        <p class="description d-none d-md-inline-block mb-0">Browse our 50 beautiful handcrafted components offered in the Free version.</p>
                      </div>
                    </a>
                  </div>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a href="#" class="nav-link" data-toggle="dropdown" href="#" role="button">
                  <i class="ni ni-collection d-lg-none"></i>
                  <span class="nav-link-inner--text">Pages</span>
                </a>
                <div class="dropdown-menu">
                  <%= link_to 'Pricing', pricing_pages_path, class: 'dropdown-item' %>
                  <%= link_to 'Profile', profile_pages_path, class: 'dropdown-item' %>
                  <%= link_to 'Login', new_user_session_path, class: 'dropdown-item' %>
                  <%= link_to 'Register', new_user_registration_path, class: 'dropdown-item' %>
                </div>
              </li>
            </ul>
            <ul class="navbar-nav align-items-lg-center ml-lg-auto">
              <li class="nav-item">
                <a class="nav-link nav-link-icon" href="https://www.instagram.com/hash32co" target="_blank" data-toggle="tooltip" title="Follow us on Instagram">
                  <i class="fa fa-instagram"></i>
                  <span class="nav-link-inner--text d-lg-none">Instagram</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link nav-link-icon" href="https://twitter.com/hash32co" target="_blank" data-toggle="tooltip" title="Follow us on Twitter">
                  <i class="fa fa-twitter-square"></i>
                  <span class="nav-link-inner--text d-lg-none">Twitter</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link nav-link-icon" href="https://github.com/hash32" target="_blank" data-toggle="tooltip" title="Star us on Github">
                  <i class="fa fa-github"></i>
                  <span class="nav-link-inner--text d-lg-none">GitHub</span>
                </a>
              </li>
              <%- if !current_user %>
                <li class="nav-item d-none d-lg-block ml-lg-4">
                  <%= link_to new_user_session_path, class: 'btn btn-neutral btn-icon' do %>
                    <span class="btn-inner--icon">
                      <i class="fa fa-user mr-2"></i>
                    </span>
                    <span class="nav-link-inner--text">Login</span>
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item d-none d-lg-block ml-lg-4">
                  <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-info btn-icon' do %>
                    <span class="btn-inner--icon">
                      <i class="fa fa-sign-out mr-2"></i>
                    </span>
                    <span class="nav-link-inner--text">Sign Out</span>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer class="footer">

      <div class="container">
        <div class="row row-grid align-items-center my-md">
          <div class="col-lg-6">
            <h3 class="text-primary font-weight-light mb-2">Thank you for supporting us!</h3>
            <h4 class="mb-0 font-weight-light">Let's get in touch on any of these platforms.</h4>
          </div>
          <div class="col-lg-6 text-lg-right btn-wrapper">
            <a target="_blank" href="https://twitter.com/hash32co" class="btn btn-neutral btn-icon-only btn-twitter btn-round btn-lg" data-toggle="tooltip" data-original-title="Follow us">
              <i class="fa fa-twitter"></i>
            </a>
            <a target="_blank" href="https://github.com/hash32" class="btn btn-neutral btn-icon-only btn-github btn-round btn-lg" data-toggle="tooltip" data-original-title="Star on GitHub">
              <i class="fa fa-github"></i>
            </a>
          </div>
        </div>
        <hr>
        <div class="row align-items-center justify-content-md-between">
          <div class="col-md-6">
            <div class="copyright">
              &copy; 2018
              <a href="https://www.hash32.com" target="_blank">HASH32</a>.
            </div>
          </div>
          <div class="col-md-6">
            <ul class="nav nav-footer justify-content-end">
              <li class="nav-item">
                <a href="https://www.creative-tim.com/product/argon-design-system" class="nav-link" target="_blank">Built with Argon</a>
              </li>

              <li class="nav-item">
                <a href="https://www.hash32.com" class="nav-link" target="_blank">HASH32</a>
              </li>

              <li class="nav-item">
                <a href="http://blog.hash32.com" class="nav-link" target="_blank">Blog</a>
              </li>

              <li class="nav-item">
                <a href="https://github.com/HASH32/duplex-rails/blob/master/LICENSE.md" class="nav-link" target="_blank">MIT License</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/pages/pricing.html.erb
<div class="position-relative">
  <!-- shape Hero -->
  <section class="section section-lg section-shaped pb-250">
    <div class="shape shape-style-1 bg-gradient-default">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
    </div>
    <div class="container py-lg-md d-flex">
      <div class="col px-0">
        <div class="row justify-content-center">
          <div class="col-lg-12 text-center">
            <h1 class="display-3  text-white"> Pick a plan. Build faster with AppLib.
              <span>Try for free for 14 days.</span>
            </h1>
            <h3></h3>
            <p class="lead text-white">
              AppLib by HASH32 comes with pre-built components to help you get started faster.
            </p>
          </div>
        </div>
      </div>
    </div>
    <!-- SVG separator -->
    <div class="separator separator-bottom separator-skew">
      <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
        <polygon class="fill-white" points="2560 0 2560 100 0 100"></polygon>
      </svg>
    </div>
  </section>
  <!-- 1st Hero Variation -->
</div>
<section class="section section-lg pt-lg-0 mt--200">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-12">
        <div class="row row-grid">
          <div class="col-lg-4">
            <div class="card card-lift--hover shadow border-0">
              <div class="card-body py-5">
                <div class="icon icon-shape icon-shape-primary rounded-circle mb-4">
                  <i class="ni ni-check-bold"></i>
                </div>
                <h6 class="text-primary text-uppercase">Download Argon</h6>
                <p class="description mt-3">Argon is a great free UI package based on Bootstrap 4 that includes the most important components and features.</p>
                <div>
                  <span class="badge badge-pill badge-primary">design</span>
                  <span class="badge badge-pill badge-primary">system</span>
                  <span class="badge badge-pill badge-primary">creative</span>
                </div>
                <a href="#" class="btn btn-primary mt-4">Learn more</a>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="card card-lift--hover shadow border-0">
              <div class="card-body py-5">
                <div class="icon icon-shape icon-shape-success rounded-circle mb-4">
                  <i class="ni ni-istanbul"></i>
                </div>
                <h6 class="text-success text-uppercase">Build Something</h6>
                <p class="description mt-3">Argon is a great free UI package based on Bootstrap 4 that includes the most important components and features.</p>
                <div>
                  <span class="badge badge-pill badge-success">business</span>
                  <span class="badge badge-pill badge-success">vision</span>
                  <span class="badge badge-pill badge-success">success</span>
                </div>
                <a href="#" class="btn btn-success mt-4">Learn more</a>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="card card-lift--hover shadow border-0">
              <div class="card-body py-5">
                <div class="icon icon-shape icon-shape-warning rounded-circle mb-4">
                  <i class="ni ni-planet"></i>
                </div>
                <h6 class="text-warning text-uppercase">Prepare Launch</h6>
                <p class="description mt-3">Argon is a great free UI package based on Bootstrap 4 that includes the most important components and features.</p>
                <div>
                  <span class="badge badge-pill badge-warning">marketing</span>
                  <span class="badge badge-pill badge-warning">product</span>
                  <span class="badge badge-pill badge-warning">launch</span>
                </div>
                <a href="#" class="btn btn-warning mt-4">Learn more</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="faq">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 mx-auto text-center">
        <h1>Frequently Asked Questions</h1>
        <p>-</p>


        <div class="row text-left">
          <div class="col-lg-6 col-md-6 col-sm-12">
            <h3>Do you provide customer support? </h3>
            <p>Yes, we do. For customizations and other projects contact us at support@hash32.com</p>
          </div>
          <div class="col-lg-6 col-md-6 col-sm-12">
            <h3>What is onboarding support? </h3>
            <p>With a powerful intuitive user interface, managing employee records becomes a breeze! You don't have to search through spreadsheets, and a document folder for your employee data again. Track leaves and expenses. Means you save a lot of your time.</p>
          </div>
          <div class="col-lg-6 col-md-6 col-sm-12">
            <h3>I need a new feature, will you build it?</h3>
            <p>In short yes! But we filter the requests through our strong innate judgement before we proceed further with development!</p>
          </div>
          <div class="col-lg-6 col-md-6 col-sm-12">
            <h3>I'm not satisfied. Do I get a refund?</h3>
            <p>Yes, email us at support@hash32.com.</p>
          </div>
          <div class="col-lg-6 col-md-6 col-sm-12">
            <h3>Do you have a minimum contract?</h3>
            <p>If it fits, i sits stuff and things, tuxedo cats always looking dapper sit and stare but find something else more interesting. And sometimes switches in french and say "miaou" just because well why not if human is on laptop sit on the keyboard.</p>
          </div>

          <div class="col-lg-6 col-md-6 col-sm-12">
            <h3>How often are the components updated?</h3>
            <p>Only hardcore masochists enjoy building HTML emails, so we’ve saved you the pain and built all the emails you’ll need as beautiful HTML templates. </p>
          </div>
        </div>
        <p>-</p>

        <div class="row row-grid justify-content-center">
          <div class="col-lg-8 text-center">
            <h2 class="display-3">Have more questions?
              <span class="text-success">We are happy to help!</span>
            </h2>
            <p class="lead">Send us an email to <a href="mailto:support@hash32.com">support@hash32.com</a> and we will get back to you as soon as possible!</p>

          </div>
        </div>

      </div>
    </div>
  </div>
</section>

app/views/pages/profile.html.erb
<main class="profile-page">
  <section class="section-profile-cover section-shaped my-0">
    <!-- Circles background -->
    <div class="shape shape-style-1 shape-primary alpha-4">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
    </div>
    <!-- SVG separator -->
    <div class="separator separator-bottom separator-skew">
      <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
        <polygon class="fill-white" points="2560 0 2560 100 0 100"></polygon>
      </svg>
    </div>
  </section>
  <section class="section">
    <div class="container">
      <div class="card card-profile shadow mt--300">
        <div class="px-4">
          <div class="row justify-content-center">
            <div class="col-lg-3 order-lg-2">
              <div class="card-profile-image">
                <a href="#">
                  <%= image_tag 'team/profile4.jpg', class: 'rounded-circle' %>
                </a>
              </div>
            </div>
            <div class="col-lg-4 order-lg-3 text-lg-right align-self-lg-center">
              <div class="card-profile-actions py-4 mt-lg-0">
                <a href="#" class="btn btn-sm btn-info mr-4">Connect</a>
                <a href="#" class="btn btn-sm btn-default float-right">Message</a>
              </div>
            </div>
            <div class="col-lg-4 order-lg-1">
              <div class="card-profile-stats d-flex justify-content-center">
                <div>
                  <span class="heading">22</span>
                  <span class="description">Friends</span>
                </div>
                <div>
                  <span class="heading">10</span>
                  <span class="description">Photos</span>
                </div>
                <div>
                  <span class="heading">89</span>
                  <span class="description">Comments</span>
                </div>
              </div>
            </div>
          </div>
          <div class="text-center mt-5">
            <h3>Jessica Jones
              <span class="font-weight-light">, 27</span>
            </h3>
            <div class="h6 font-weight-300"><i class="ni location_pin mr-2"></i>Bucharest, Romania</div>
            <div class="h6 mt-4"><i class="ni business_briefcase-24 mr-2"></i>Solution Manager - Creative Tim Officer</div>
            <div><i class="ni education_hat mr-2"></i>University of Computer Science</div>
          </div>
          <div class="mt-5 py-5 border-top text-center">
            <div class="row justify-content-center">
              <div class="col-lg-9">
                <p>An artist of considerable range, Ryan — the name taken by Melbourne-raised, Brooklyn-based Nick Murphy — writes, performs and records all of his own music, giving it a warm, intimate feel with a solid groove structure. An artist of considerable range.</p>
                <a href="#">Show more</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>